### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Janesh1** [jigoshop/Jigoshop-eCommerce#83]
On trying to activate JigoShop 2 on a brand new installation, l receive the following error:

Plugin could not be activated because it triggered a fatal error.

Unable to create Jigoshop tables.

Running WordPress 4.6.1 and Linux / Apache / PHP 5.6

**Comment by kkasowski** [comment]
Hi Janesh1,

Please check jigoshop.log file in jigoshop log directory.

**Comment by Janesh1** [comment]
[01-Nov-2016 01:54:36 UTC] WordPress database error Can't create table `1021840_crin`.`wp_jigoshop_product_attribute_meta` (errno: 121 "Duplicate key on write or update") for query 
            CREATE TABLE IF NOT EXISTS wp_jigoshop_product_attribute_meta (
                id INT(9) NOT NULL AUTO_INCREMENT,
                product_id BIGINT(20) UNSIGNED NOT NULL,
                attribute_id INT(9) NOT NULL,
                meta_key VARCHAR(255) NOT NULL,
                meta_value TEXT NOT NULL,
                PRIMARY KEY id (id),
                FOREIGN KEY product_attribute (product_id, attribute_id) REFERENCES wp_jigoshop_product_attribute (product_id, attribute_id) ON DELETE CASCADE
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
         made by do_action('activate_jigoshop-ecommerce/jigoshop.php'), call_user_func_array, JigoshopInit->update, Jigoshop\Core\Installer->install, Jigoshop\Core\Installer->_createTables

**Comment by Janesh1** [comment]
From the jigoshop.log

[2016-11-01 01:54:36] jigoshop.CRITICAL: Unable to create table "jigoshop_product_attribute_meta". Error: "Can't create table `1021840_crin`.`wp_jigoshop_product_attribute_meta` (errno: 121 "Duplicate key on write or update")".

**Comment by kkasowski** [comment]
@cff8642 this should fix the problem.

**Comment by Janesh1** [comment]
Thanks for the update.

I had to create one more table manually.  It's all working now ;)

Might want to commit this:

[01-Nov-2016 22:39:27 UTC] WordPress database error Can't create table `1021840_crin`.`wp_jigoshop_product_attachment` (errno: 121 "Duplicate key on write or update") for query 
            CREATE TABLE IF NOT EXISTS wp_jigoshop_product_attachment (
                product_id BIGINT(20) UNSIGNED NOT NULL,
                attachment_id BIGINT(20) UNSIGNED NOT NULL,
                type VARCHAR(50) NOT NULL,
                FOREIGN KEY attachment (attachment_id) REFERENCES  wp_posts (ID) ON DELETE CASCADE,
                FOREIGN KEY product (product_id) REFERENCES wp_posts (ID) ON DELETE CASCADE
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
         made by do_action('activate_jigoshop-ecommerce/jigoshop.php'), call_user_func_array, JigoshopInit->update, Jigoshop\Core\Installer->install, Jigoshop\Core\Installer->_createTables
