### ISSUE TITLE
Cannot manage stock for product variations

### ISSUE THREAD

**Issue by grittyshaker** [jigoshop/Jigoshop-eCommerce#86]
Hi,

In Jigoshop 1.18.2, you can manage the stock for product variations and the stock availability will be visible on the frontend for each variation.

In Jigoshop 2.0.2, you cannot manage the stock for product variations. On each variation, there is a field for entering the number of stock but it doesn't appear to do anything?

**Comment by kkasowski** [comment]
Product variations are hardcoded to have "manage stock" set to true.

https://github.com/jigoshop/Jigoshop2/blob/master/src/Jigoshop/Service/Product/VariableService.php#L109
