### ISSUE TITLE
I can't change the Bank Account under Payment on my Website.

### ISSUE THREAD

**Issue by benedikt-buchert** [jigoshop/Jigoshop-eCommerce#90]
I noticed that whatever is inserted under the field with th id= _bank_transfer_bank_name is also automatically inserted into fields with the following id's: _bank_transfer_sort_code, _bank_transfer_iban, _bank_transfer_bic

No Errors are thrown....

[Image](http://imgur.com/a/Nf7wP)

**Comment by kkasowski** [comment]
Hi,
As I can see, this is a display issue on the admin panel. On the checkout page, the fields should be displayed correctly. We are planning to release a new version tomorrow and this issue will be fixed.

**Comment by benedikt-buchert** [comment]
Issue is fixed thank you!

**Comment by benedikt-buchert** [comment]
Is it also possible to add the bank details dynamically into the email template?
